### PR TITLE
Howto debug Basic with the python debugger pdb

### PR DESCRIPTION
**Pull request by schlatterbeck**

### CODE REVIEW

**Comment by robhagemans** [comment]
Thanks for documenting this! I'm thinking, perhaps this is better in the wiki rather than as a new/additional file in the tree? 

The same probably holds for `HACKING.md` itself by the way, only that was written before moving this onto GitHub or before I noticed it had a wiki built-in. I'll probably move that as well.

**Comment by robhagemans** [comment]
I've added this to the wiki, please see here: 
https://github.com/robhagemans/pcbasic/wiki/Debugging-Basic-with-the-Python-Debugger 

Thanks!

**Comment by schlatterbeck** [comment]
On Fri, Jul 01, 2022 at 01:35:08PM -0700, Rob Hagemans wrote:
> I've added this to the wiki, please see here: 
> https://github.com/robhagemans/pcbasic/wiki/Debugging-Basic-with-the-Python-Debugger 

Thanks, and thanks again for your support!

Ralf
-- 
Dr. Ralf Schlatterbeck                  Tel:   +43/2243/26465-16
Open Source Consulting                  www:   www.runtux.com
Reichergasse 131, A-3411 Weidling       email: ***@***.***

**Comment by schlatterbeck** [comment]
On Thu, Jun 23, 2022 at 01:22:21PM -0700, Rob Hagemans wrote:
> Thanks for documenting this! I'm thinking, perhaps this is better in
> the wiki rather than as a new/additional file in the tree? 
> 
> The same probably holds for `HACKING.md` itself by the way, only that
> was written before moving this onto GitHub or before I noticed it had
> a wiki built-in. I'll probably move that as well.

Fine with me, use it for whatever you think fits!

Ralf
-- 
Dr. Ralf Schlatterbeck                  Tel:   +43/2243/26465-16
Open Source Consulting                  www:   www.runtux.com
Reichergasse 131, A-3411 Weidling       email: ***@***.***

**Pull request closed without merging**
